DoAnQLBS/Controllers/ChuDeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using DoAnQLBS.Models;

namespace DoAnQLBS.Controllers
{
    public class ChuDeController : Controller
    {
        // GET: ChuDe
        QLBSEntities db = new QLBSEntities();
        public PartialViewResult ChuDePartial()
        {
            return PartialView(db.CHUDEs.Take(5).ToList());
        }
        public ViewResult ChuDeSach(int machude=0)
        {
            CHUDE cd = db.CHUDEs.SingleOrDefault(b => b.MACHUDE == machude);
            if (cd == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            List<SACH> sach = db.SACHes.Where(n=>n.MACHUDE == machude).OrderBy(b=>b.GIABAN).ToList();
            if(sach.Count == 0)
            {
                ViewBag.sach = "Không có sách nào thuộc chủ đề này";
            }
            return View(sach);
        }
        public ViewResult DanhMucChuDe()
        {
            return View(db.CHUDEs.ToList());
        }
    }
}

DoAnQLBS/Controllers/NXBController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoAnQLBS.Models;

namespace DoAnQLBS.Controllers
{
    public class NXBController : Controller
    {
        // GET: NXB
        QLBSEntities db = new QLBSEntities();
        public PartialViewResult NXBPartial()
        {
            return PartialView(db.NXBs.Take(5).OrderBy(n => n.TENNXB).ToList());
        }
        public ViewResult sachtheonxb(int manxb=0)
        {
            NXB nxb = db.NXBs.SingleOrDefault(b => b.MANXB == manxb);
            if (nxb == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            List<SACH> sach = db.SACHes.Where(n => n.MANXB == manxb).OrderBy(b => b.GIABAN).ToList();
            if (sach.Count == 0)
            {
                ViewBag.sach = "Sách vẫn chưa nhập về mong quý khách thông cảm";
            }
            return View(sach);
        }
        public ViewResult DanhMucNXB()
        {
            return View(db.NXBs.ToList());
        }
    }
}

DoAnQLBS/Controllers/SachController.cs
using DoAnQLBS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoAnQLBS.Models;

namespace DoAnQLBS.Controllers
{
    public class SachController : Controller
    {
        // GET: Sach
        QLBSEntities db = new QLBSEntities();
        public PartialViewResult SachPartial()
        {
            var lstsach = db.SACHes.Take(3).ToList();
            return PartialView(lstsach);
        }
        public ViewResult xemchitiet(int MaSach=0)
        {
            SACH sach = db.SACHes.SingleOrDefault(b => b.MASACH == MaSach);
            if(sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sach);
        }
    }
}

DoAnQLBS/Views/Layout/Admin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="https://fonts.googleapis.com/css2?family=Alef:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href="~/Content/NguoiDungCSSLayOut/styles.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info py-0 fixed-top">
        <a class="navbar-brand" href="~/Admin/Index">Trang Admin</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <ul class="side-bar">
                <li class="active">
                    <a href="~/Admin/Index">
                        <i class="fas fa-tachometer-alt fa-fw"></i>
                        Quản lý sản phẩm
                    </a>
                </li>
               
            </ul>

            <ul class="navbar-nav ml-auto">
               
                <li class="nav-item">
                    <a class="nav-link px-3" href="/Khachhang/DangXuat">
                        Đăng xuất
                    </a>
                </li>
            </ul>


        </div>
    </nav>

    <section class="content">

        <h1>Sản phẩm</h1>
        @RenderBody()
    </section>



    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"></script>
    <script>
        $(document).ready(function () {
            "use strict";
            var height = $(window).height();
            var navbar_top = $('.navbar').outerHeight();
            var slide_bar = $('.side-bar').height();
            $('.content').css('min-height', height);
            $('.side-bar').css('top', navbar_top);
            $('.side-bar').css('height', height - navbar_top)
            $('.side-bar').css('height', height + 20)
        });
    </script>
</body>
</html>

DoAnQLBS/Views/Layout/Nguoidung.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @*Chen link css cua template ban sach*@
    <link href="~/Content/NguoiDungCSSLayOut/fonts.css" rel="stylesheet" />
    <link href="~/Content/NguoiDungCSSLayOut/screen.css" rel="stylesheet" />
    @*Chen link css thiet ke nguoi dung*@
    <link href="~/Content/NguoiDungCSSLayOut/NguoiDung.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script> 
</head>
<body>
    <div id="ToanTrang">
        <section class="blank">
            <div class="flash">
                <div class="sodienthoai">
                    <i class="fa fa-phone">
                        0865632776
                    </i>
                </div>
                <div class="DangKyDangNhap">
                    @*Dang ky va dang nhap*@
                    @if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")
                    {

                        @Html.Action("GioHangPartial", "GioHang")
                        <i class="fa fa-user-plus"></i>
                        <a href="/Khachhang/DangKy">Đăng ký</a>
                        <i class="fa fa-sign-in"></i>
                        <a href="/Khachhang/DangNhap">Đăng nhập</a>
                    }
                    else
                    {
                        @Html.Action("GioHangPartial", "GioHang")
                        <i class="fa fa-user-plus"></i>
                        <a href="/Khachhang/DangKy">Đăng ký</a>
                        <i class="fa fa-sign-in"></i>
                        <a href="/Khachhang/DangNhap">Đổi tài khoản</a>
                    }
                </div>

                </div>

            <div class="flash" id="danhmuc">
                <div id="timkiem">
                    @using (Html.BeginForm("KetQua","TimKiem",FormMethod.Post))
                    {
                        @Html.TextBox("timkiem", "", new { @class = "txtTimKiem", @placeholder = "Nhập vào sách cần tìm" })
                        <div class="nuttimkiem">
                            <button type="submit"><i class="fa fa-search"></i></button>
                        </div>
                    }
                </div>
                <ul class="navMenu">
                    <li>
                        <a href="~/Home/Index">Trang chủ</a>
                    </li>
                    <li>
                        <a href="~/GioiThieu/Index">Giới thiệu</a>
                    </li>
                    <li>
                        <a href="~/Lienhe/Index">Liên hệ</a>
                    </li>
                </ul>
            </div>
        </section>
        <section id="phantren">
            <div id="menuTrai">
                @* Dung partial view de chen sach vao *@
                <div class="activity">
                    @Html.Action("SachPartial","Sach")
                </div>
            </div>
            <div id="chinhanh">
                <img src="~/Hinh anh/9210ad11-08b5-4fae-a5fe-7556343ca9e9.jpg" height="320" />
            </div>
        </section>
        <section>
            @* xuong dong div o duoi *@
            <div style="clear:both"></div>
        </section>
        <div id="noidung">
            @RenderBody()
        </div>
        <section>
            <div id="danhmucchude">
                @Html.Action("ChuDePartial","ChuDe")
            </div>

        </section>

        <section class="blank items">
            <div id="nxbtrai">
                <div class="item">
                    <div class="item-info">
                        @Html.Action("NXBPartial", "NXB")
                    </div>
                </div>
                
            </div>
                <div id="nxbphai">
                    @RenderSection("NoiDungBenPhai",false)
                </div>
                <div style="clear:both"></div>
                <div id="phanduoi">
                    <a href="#" class="button button-buy">Chào mừng các bạn đã đến với trang web bán sách của mình</a>
                </div>     
        </section>
    </div>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>